version: '3.7'

services:
  app:
    build:
      context: .
      target: dev
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        OSTYPE: ${OSTYPE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bakken-shop.rule=Host(`pokedex.local`)"
      - "traefik.http.routers.bakken-shop.tls=false"
      - "traefik.http.routers.bakken-shop.entrypoints=web"
      - "traefik.http.services.bakken-shop.loadbalancer.server.port=80"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: "o7%N3pm8Z76s3emHUjMv"
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      PHP_IDE_CONFIG: "serverName=pokedex"
      XDEBUG_SESSION: PHPSTORM
    volumes:
      - .:/www:delegated

networks:
  default:
    name: pokedex
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.93.0/24
